# Proyecto Modelos y Simulación de Sistemas I

## Exploración de datos

In [53]:
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install opendatasets

Requirement already satisfied: numpy in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (2.2.5)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from seaborn) (2.2.5)
Requirement already satisfied: pandas>=1.2 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: opendatasets in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (0.1.22)
Requirement already satisfied: tqdm in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from opendatasets) (1.7.4.2)
Requirement already satisfied: click in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from opendatasets) (8.1.8)
Requirement already satisfied: bleach in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (2025.1.31)
Requirement already satisfied: charset-normalizer in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (3.4.1)
Requirement already satisfied: idna in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (3.10)
Requirement already satisfied: protobuf in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (6.30.2)
Requirement already satisfied: python-dateutil>=2.5.3 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (75.8.0)
Requirement already satisfied: six>=1.10 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (2.4.0)
Requirement already satisfied: webencodings in /root/miniconda3/envs/modelos/lib/python3.11/site-packages (from kaggle->opendatasets) (0.5.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import opendatasets as od
import os

In [55]:
link = "https://www.kaggle.com/competitions/udea-ai-4-eng-20251-pruebas-saber-pro-colombia"
od.download(link)

Skipping, found downloaded files in "./udea-ai-4-eng-20251-pruebas-saber-pro-colombia" (use force=True to force download)

## Análisis inicial de datos

In [56]:
# Cargar el conjunto de datos
df = pd.read_csv('udea-ai-4-eng-20251-pruebas-saber-pro-colombia/train.csv')
df.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              692500 non-null  int64
 1   PERIODO                         692500 non-null  int64
 2   ESTU_PRGM_ACADEMICO             692500 non-null  object
 3   ESTU_PRGM_DEPARTAMENTO          692500 non-null  object
 4   ESTU_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   ESTU_HORASSEMANATRABAJA         661643 non-null  object
 6   FAMI_ESTRATOVIVIENDA            660363 non-null  object
 7   FAMI_TIENEINTERNET              665871 non-null  object
 8   FAMI_EDUCACIONPADRE             669322 non-null  object
 9   FAMI_TIENELAVADORA              652727 non-null  object
 10  FAMI_TIENEAUTOMOVIL             648877 non-null  object
 11  ESTU_PRIVADO_LIBERTAD           692500 non-null  object
 12  ESTU_PAGOMATRICULAPROPIO        686002 non-null  object
 13  FAMI_TIENECOMPUTADOR            654397 non-null  object
 14  FAMI_TIENEINTERNET.1            665871 non-null  object
 15  FAMI_EDUCACIONMADRE             668836 non-null  object
 16  RENDIMIENTO_GLOBAL              692500 non-null  object
 17  coef_1                          692500 non-null  float64
 18  coef_2                          692500 non-null  float64
 19  coef_3                          692500 non-null  float64
 20  coef_4                          692500 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 111.0+ MB

In [58]:
df.describe()

,ID,PERIODO,coef_1,coef_2,coef_3,coef_4
count,692500.000000,692500.000000,692500.000000,692500.000000,692500.000000,692500.000000
mean,494606.130576,20198.366679,0.268629,0.259996,0.262087,0.262903
std,285585.209455,10.535037,0.122130,0.093480,0.058862,0.067944
min,1.000000,20183.000000,0.000000,0.000000,0.000000,0.000000
25%,247324.750000,20195.000000,0.203000,0.212000,0.254000,0.255000
50%,494564.500000,20195.000000,0.240000,0.271000,0.276000,0.285000
75%,741782.500000,20203.000000,0.314000,0.309000,0.293000,0.303000
max,989286.000000,20213.000000,0.657000,0.487000,0.320000,0.332000

In [59]:
# Cantidad de registros
print(f"Cantidad de registros: {df.shape[0]}")

# Cantidad de columnas
print(f"Cantidad de columnas: {df.shape[1]}")

# Cantidad de valores nulos
print(f"Cantidad de valores nulos: {df.isnull().sum().sum()}")

Cantidad de registros: 692500
Cantidad de columnas: 21
Cantidad de valores nulos: 297378

In [60]:
# Lista de estudiantes por programa académico
estudiantes_por_programa = df['ESTU_PRGM_ACADEMICO'].value_counts()
print(estudiantes_por_programa)

ESTU_PRGM_ACADEMICO
DERECHO                                                                 53244
ADMINISTRACION DE EMPRESAS                                              51902
CONTADURIA PUBLICA                                                      39664
PSICOLOGIA                                                              31932
INGENIERIA INDUSTRIAL                                                   28481
                                                                        ...
ADMINISTRACIÓN DE EMPRESAS TURISTICAS POR CICLOS - CICLO PROFESIONAL        1
QUIMICA Y FARMACIA                                                          1
LICENCIATURA EN EDUCACON FISICA, RECREACION Y DEPORTES                      1
COMUNICACIÓN SOCIAL Y PERIODISMO                                            1
PROFESIONAL EN INVESTIGACIÓN CRIMINAL                                       1
Name: count, Length: 948, dtype: int64

In [61]:
# Lista de estudiantes por estrato
estudiantes_por_estrato = df['FAMI_ESTRATOVIVIENDA'].value_counts()
print(estudiantes_por_estrato)

FAMI_ESTRATOVIVIENDA
Estrato 2      232671
Estrato 3      210685
Estrato 1      111991
Estrato 4       65514
Estrato 5       23608
Estrato 6       12605
Sin Estrato      3289
Name: count, dtype: int64

In [62]:
#Programas académicos más populares
programas_mas_populares = df['ESTU_PRGM_ACADEMICO'].value_counts().head(10)
print(programas_mas_populares)

ESTU_PRGM_ACADEMICO
DERECHO                       53244
ADMINISTRACION DE EMPRESAS    51902
CONTADURIA PUBLICA            39664
PSICOLOGIA                    31932
INGENIERIA INDUSTRIAL         28481
ADMINISTRACIÓN DE EMPRESAS    24777
INGENIERIA CIVIL              19487
MEDICINA                      18099
PSICOLOGÍA                    17377
INGENIERIA DE SISTEMAS        17150
Name: count, dtype: int64